// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"

	"github.com/1f349/violet/target"
)

type Domain struct {
	ID     int32  `json:"id"`
	Domain string `json:"domain"`
	Active bool   `json:"active"`
}

type Favicon struct {
	ID   int32          `json:"id"`
	Host string         `json:"host"`
	Svg  sql.NullString `json:"svg"`
	Png  sql.NullString `json:"png"`
	Ico  sql.NullString `json:"ico"`
}

type Redirect struct {
	ID          int32        `json:"id"`
	Source      string       `json:"source"`
	Destination string       `json:"destination"`
	Description string       `json:"description"`
	Flags       target.Flags `json:"flags"`
	Code        int32        `json:"code"`
	Active      bool         `json:"active"`
}

type Route struct {
	ID          int32        `json:"id"`
	Source      string       `json:"source"`
	Destination string       `json:"destination"`
	Description string       `json:"description"`
	Flags       target.Flags `json:"flags"`
	Active      bool         `json:"active"`
}
