// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	AddDomain(ctx context.Context, arg AddDomainParams) error
	AddRedirect(ctx context.Context, arg AddRedirectParams) error
	AddRoute(ctx context.Context, arg AddRouteParams) error
	DeleteDomain(ctx context.Context, domain string) error
	GetActiveDomains(ctx context.Context) ([]string, error)
	GetActiveRedirects(ctx context.Context) ([]GetActiveRedirectsRow, error)
	GetActiveRoutes(ctx context.Context) ([]GetActiveRoutesRow, error)
	GetAllRedirects(ctx context.Context) ([]GetAllRedirectsRow, error)
	GetAllRoutes(ctx context.Context) ([]GetAllRoutesRow, error)
	GetFavicons(ctx context.Context) ([]GetFaviconsRow, error)
	RemoveRedirect(ctx context.Context, source string) error
	RemoveRoute(ctx context.Context, source string) error
	UpdateFaviconCache(ctx context.Context, arg UpdateFaviconCacheParams) error
}

var _ Querier = (*Queries)(nil)
