on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.x]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
    - run: sudo add-apt-repository ppa:inkscape.dev/stable
    - run: sudo apt-get update
    - run: sudo apt-get install inkscape -y
    - run: go build ./cmd/violet/
    - run: go test ./...
