on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.22.x]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
    - run: sudo add-apt-repository ppa:inkscape.dev/stable
    - run: sudo apt-get update
    - run: sudo apt-get install inkscape -y
    - name: Set up MariaDB
      id: mariadb
      uses: rusher/action-setup-mariadb@v1.6
      with:
        tag: '11.4'
        local: true  # Force local installation
        root-password: 'myRootPassword'
        database: 'myDb'
    - run: go build ./cmd/violet/
    - run: DB=root:myRootPassword@tcp(127.0.0.1)/maildepo go test ./...
